export const TABLE_HEAD = [
  "EmployeeId",
  "First Name",
  "Last Name",
  "Business Unit",
  "",
];
export const PROGRESS_HEAD=[
  "EmployeeId",
  "First Name",
  "Last Name",
  "Business Unit",
  "Progress",
]

export const TABLE_ROWS = [
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-3.jpg",
    name: "John Michael",
    email: "john@creative-tim.com",
    job: "Manager",
    org: "Organization",
    employeeId: 1001,
    buisnessUnit: "TELCO",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-2.jpg",
    name: "Alexa Liras",
    email: "alexa@creative-tim.com",
    job: "Programator",
    org: "Developer",
    employeeId: 1002,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-1.jpg",
    name: "Laurent Perrier",
    email: "laurent@creative-tim.com",
    job: "Executive",
    org: "Projects",
    employeeId: 1003,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-4.jpg",
    name: "Michael Levi",
    email: "michael@creative-tim.com",
    job: "Programator",
    org: "Developer",
    employeeId: 1004,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-5.jpg",
    name: "Richard Gran",
    email: "richard@creative-tim.com",
    job: "Manager",
    org: "Executive",
    employeeId: 1005,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-6.jpg",
    name: "Emma Watson",
    email: "emma@creative-tim.com",
    job: "Designer",
    org: "Creative",
    employeeId: 1006,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-7.jpg",
    name: "Chris Hemsworth",
    email: "chris@creative-tim.com",
    job: "Engineer",
    org: "Tech",
    employeeId: 1007,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-8.jpg",
    name: "Scarlett Johansson",
    email: "scarlett@creative-tim.com",
    job: "Manager",
    org: "Marketing",
    employeeId: 1008,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-9.jpg",
    name: "Tom Cruise",
    email: "tom@creative-tim.com",
    job: "Actor",
    org: "Entertainment",
    employeeId: 1009,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-10.jpg",
    name: "Jennifer Lawrence",
    email: "jennifer@creative-tim.com",
    job: "Actress",
    org: "Entertainment",
    employeeId: 1010,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-11.jpg",
    name: "Leonardo DiCaprio",
    email: "leo@creative-tim.com",
    job: "Actor",
    org: "Entertainment",
    employeeId: 1011,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-12.jpg",
    name: "Angelina Jolie",
    email: "angelina@creative-tim.com",
    job: "Actress",
    org: "Entertainment",
    employeeId: 1012,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-13.jpg",
    name: "Brad Pitt",
    email: "brad@creative-tim.com",
    job: "Actor",
    org: "Entertainment",
    employeeId: 1013,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-14.jpg",
    name: "Meryl Streep",
    email: "meryl@creative-tim.com",
    job: "Actress",
    org: "Entertainment",
    employeeId: 1014,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
  {
    img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-15.jpg",
    name: "Robert Downey Jr.",
    email: "robert@creative-tim.com",
    job: "Actor",
    org: "Entertainment",
    employeeId: 1015,
    buisnessUnit: "NBU-CDEC",
    checked: false,
  },
];
